version: '3'

services:

  web:
    image: 'nginx:1.13.8-alpine'
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
        # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    command: [nginx-debug, '-g', 'daemon off;']

  pg:
    image: 'postgres:10.1-alpine'
  environment:
    POSTGRES_USER: 'fullstack'
    POSTGRES_PASSWORD: 'PGfullstack@123'
    POSTGRES_DB: 'fullstack_dev'
    PGDATA: /var/lib/postgresql/data/pgdata
  volumes:
    - ./postgres/pgdata:/var/lib/postgresql/data/pgdata
  ports:
    - 54321:5432
  pgadmin:
    image: 'chorss/docker-pgadmin4'
  ports:
    - 5050:5050

  # TODO Revistar este item. Talvez não seja preciso mais construir a própria imagem
  wildfly:
    build:
      context: ./wildfly
    image: fullstack_wildfly:0.1.0
    ports:
      - 8888:8080 #web server
      - 8890:9990 #admin console
      - 8443:8443 #HTTPS listener

  mssql:
    build:
      context: ./mssql
    image: 'mssql-fts:2017'
    ports:
      - '1401:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PGfullstack@123 # Verificar qual env é realmente usada
      - SA_PASSWORD=PGfullstack@123
